#!/usr/bin/env python3

# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2023 Michał Kruszewski
# https://github.com/m-kru/hbs

from datetime import datetime
import json
import os
import pathlib
import re
import subprocess
import sys

import concurrent.futures
import multiprocessing

this_script_dir = os.path.dirname(os.path.abspath(__file__))
workers = multiprocessing.cpu_count()

error_regexp = re.compile(r"(?<!\=)\berror\b")
warning_regexp = re.compile(r"(?<!\=)\bwarning\b")

def error(msg, end='\n'):
    print(msg, file=sys.stderr, end=end)
    exit(1)


if len(sys.argv) < 2:
    error("missing command, check help")


def path_has_pattern(path, patterns):
    if len(patterns) == 0:
        return True

    for pattern in patterns:
        if pattern in path:
            return True
    return False


def run_to_file(target_path):
    """ run_to_file runs given target and directs output to file. """
    build_dir = 'build'
    if 'HBS_BUILD_DIR' in os.environ:
        build_dir = os.environ['HBS_BUILD_DIR']

    log_dir = os.path.join(build_dir, target_path.replace('::', '--'))
    pathlib.Path(log_dir).mkdir(parents=True, exist_ok=True)
    log_file_path = os.path.join(log_dir, 'output.txt')
    log_file = open(log_file_path, 'w+')

    result = {'target': target_path, 'passed': False}
    global test_longest_path_len

    try:
        output = subprocess.run(
            [os.path.join(this_script_dir, 'hbs.tcl'), 'run', target_path],
            check=True,
            encoding="utf-8",
            stdout=log_file,
            stderr=log_file,
        )
        result['passed'] = True
        msg = f"{target_path.ljust(test_longest_path_len+1)} \033[92mpassed\033[0m"
    except subprocess.CalledProcessError:
        msg = f"{target_path.ljust(test_longest_path_len+1)} \033[91mfailed\033[0m"

    log_file.close()
    log = open(log_file_path, 'r')

    error_count = 0
    warning_count = 0
    for line in log:
        error_count += len(error_regexp.findall(line.lower()))
        warning_count += len(warning_regexp.findall(line.lower()))

    log.close()

    if error_count > 0:
        msg += f"  errors: {error_count}"
    if warning_count > 0:
        msg += f"  warnings: {warning_count}"

    print(msg)

    result['error_count'] = error_count
    result['warning_count'] = warning_count

    global test_results
    test_results.append(result)


test_results = []
test_longest_path_len = 0


def print_test_summary(start_time):
    """Prints tests summary and returns number of failed tests."""
    s = (datetime.now() - start_time).seconds
    hours, remainder = divmod(s, 3600)
    minutes, seconds = divmod(remainder, 60)

    global test_results

    passed = 0
    failed = 0
    errors = 0
    warnings = 0

    for r in test_results:
        if r['passed']:
            passed += 1
        else:
            failed += 1

        errors += r['error_count']
        warnings += r['warning_count']

    print()
    print(f"time:     {hours} h {minutes} min {seconds} s")
    print(f"targets:  {len(test_results)}")
    print(f"\033[92mpassed\033[0m:   {passed}")
    print(f"\033[91mfailed\033[0m:   {failed}")
    print(f"errors:   {errors}")
    print(f"warnings: {warnings}")

    return failed


def test(patterns):
    """patterns are target path patterns"""
    start_time = datetime.now()

    output = subprocess.run(
        [os.path.join(this_script_dir, 'hbs.tcl'), 'dump-json'],
        capture_output=True,
        encoding="utf-8",
    )
    if output.returncode != 0:
        error(output.stderr, end='')

    cores = json.loads(output.stdout)

    test_targets = []
    for core, core_info in cores.items():
        for target in core_info['targets']:
            if not (
                target == 'tb'
                or target.startswith('tb_')
                or target.startswith('tb-')
                or target.endswith('_tb')
                or target.endswith('-tb')
            ):
                continue

            target_path = core + '::' + target
            if path_has_pattern(target_path, patterns):
                test_targets.append(target_path)
                global test_longest_path_len
                if len(target_path) > test_longest_path_len:
                    test_longest_path_len = len(target_path)

    test_targets.sort()
    workers_count = multiprocessing.cpu_count()

    print(f"running {len(test_targets)} targets with {workers_count} workers\n")

    with concurrent.futures.ThreadPoolExecutor(max_workers=workers) as executor:
        executor.map(lambda t: run_to_file(t), test_targets)

    failed_count = print_test_summary(start_time)

    if failed_count > 0:
        exit(1)


cmd = sys.argv[1]

if cmd == "test":
    test(sys.argv[2:])
else:
    status = subprocess.run(
        [os.path.join(this_script_dir, 'hbs.tcl'), cmd, *sys.argv[2:]]
    )
    exit(status.returncode)
